#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Values marked [V] were re-derived from itel stock firmware revision 28
# (build 251212V1661) and/or the live device. Values marked [C] are carried
# forward and still want an independent check — see notes/ for status.
#

DEVICE_PATH := device/itel/S666LN

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    odm_dlkm \
    product \
    system \
    system_ext \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_boot \
    vendor_dlkm

# Architecture                                                          [V]
# Helio G99: 2x Cortex-A76 @2.2GHz + 6x Cortex-A55 @2.0GHz
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a76
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

# Bootloader                                                            [V]
TARGET_BOOTLOADER_BOARD_NAME := s666ln
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6789

# Kernel — GKI. This device ships a PREBUILT kernel image; the ROM does not
# compile it. See device/itel/S666LN-kernel.                             [V]
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_RAMDISK_USE_LZ4 := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096

# Stock boot.img ships an EMPTY cmdline; the one boot parameter lives in
# vendor_boot's cmdline field, and vendor_boot's bootconfig section is zero
# bytes. That is also what the build does with this variable at header v4 —
# BOARD_KERNEL_CMDLINE is passed as --vendor_cmdline, not into boot.img — so
# setting it here reproduces stock. Everything else the kernel sees
# (androidboot.hardware=mt6789 &c.) is appended by the MediaTek LK at boot,
# not stored in any image we build.
#
# NOT reproduced from the old tree: androidboot.selinux=permissive (this tree
# runs enforcing) and sysctl.kernel.sched_pelt_multiplier=4 (absent from stock
# revision 28; it is a kernel/ROM tuning choice, not a device fact).   [V]
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2

# Offsets                                                               [V]
# Read back from the stock vendor_boot header (v4, page 4096):
#   kernel_addr  0x40000000 = base + kernel_offset
#   ramdisk_addr 0x66f00000 = base + ramdisk_offset
#   tags_addr    0x47c80000 = base + tags_offset
#   dtb_addr     0x47c80000 = base + dtb_offset
# All four reconstruct exactly from the values below.
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_KERNEL_TAGS_OFFSET := 0x07c88000
BOARD_DTB_OFFSET := 0x07c88000

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)

# Kernel — built FROM SOURCE, with prebuilt dtb/dtbo/modules alongside.
#
# Only the Image is compiled. The dtb, dtbo and all 404 vendor modules (198
# vendor_dlkm + 206 vendor_boot) remain MediaTek prebuilts: they are not part of
# GKI and there is no source for them.
#
# SINGLE SOURCE OF TRUTH for the config: s666ln_defconfig lives in the kernel
# source repo at arch/arm64/configs/, is generated by the kernel project's
# build.sh (stock.config + performance + network + bore + ntsync, merged and
# olddefconfig'd) and committed there. Both the kernel project and this ROM build
# read that one file, so they cannot drift.
#
# Do NOT pass a list here. LineageOS documents TARGET_KERNEL_CONFIG as "list of
# defconfigs, first being the base", but make-kernel-config passes them straight
# to Kbuild as make targets — and stock GKI Kbuild runs them sequentially, last
# one winning, with no merge. A list would silently build the wrong config.
#
# gki_defconfig does NOT work: the config is what fixes the symbol CRCs, so a
# wrong defconfig yields a kernel that builds fine and boots nothing.
#
# ⚠ Never set KERNEL_LTO. kernel.mk honours it (thin/full/none) by rewriting
# LTO_CLANG_FULL after the defconfig is applied — which changes module_layout and
# breaks every vendor module. The KMI gate below will catch it, but the fix is to
# leave the variable alone.
TARGET_KERNEL_PACKAGE := device/itel/S666LN-kernel
TARGET_KERNEL_SOURCE := kernel/itel/S666LN
TARGET_KERNEL_CONFIG := s666ln_defconfig
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_CLANG_VERSION := r416183b

# CROSS_COMPILE must be passed even though this kernel is built entirely with
# clang, and getting that wrong does NOT fail the build -- it silently produces a
# kernel that cannot load a single vendor module.
#
# BoardConfigKernel.mk:76-86 defaults TARGET_KERNEL_NO_GCC to true for any 5.10+
# kernel ("5.10+ can fully compile without GCC"). That flag also gates the block
# that sets KERNEL_CROSS_COMPILE and KERNEL_CLANG_TRIPLE, so make is invoked with
# neither. Linux 5.10 only adds the clang target from CROSS_COMPILE:
#
#     ifneq ($(CROSS_COMPILE),)
#     CLANG_FLAGS += --target=$(notdir $(CROSS_COMPILE:%-=%))
#     endif
#
# With no target, clang assembles for the HOST. Kconfig's arm64 probes then fail,
# and the failure cascades somewhere completely unrelated:
#
#   ARM64_AS_HAS_MTE   is $(as-instr,.arch armv8.5-a+memtag / stgm ...) -> n
#   HAVE_ARCH_KASAN_HW_TAGS                                             -> n
#   KASAN_HW_TAGS      unavailable, so Kconfig picks KASAN_GENERIC
#   HAS_LTO_CLANG      depends on "!KASAN || KASAN_HW_TAGS"             -> n
#   => LTO_NONE=y and CFI_CLANG vanishes
#
# LTO_CLANG_FULL + CFI_CLANG + MODVERSIONS are precisely what reproduce
# module_layout 0x7c24b32d, so the result is a kernel that builds cleanly, boots
# nothing, and whose defconfig looked correct the whole time. Note AS_HAS_ARMV8_5
# still reports y -- it is only a cc-option, not a real assembler probe -- so the
# config looks half-right and invites the wrong conclusion.
#
# aarch64-linux-gnu- (not the aarch64-linux-android- default) matches the
# toolchain triple the KMI-verified kernel was built with.
TARGET_KERNEL_NO_GCC := false
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-gnu-
# BoardConfigKernel.mk:95 would resolve this to prebuilts/clang/host/..., which
# on a LineageOS 20 tree only ever contains clang-r450784d. r416183b is already
# in the tree at prebuilts/clang/kernel/, supplied by LineageOS's own manifest
# snippet (.repo/manifests/snippets/lineage.xml), so no local manifest entry is
# needed -- only this path override.
#
# NOTE the '=' -- this MUST be a recursively-expanded assignment. BUILD_TOP is
# not defined yet when BoardConfig.mk is parsed, so ':=' bakes in an empty
# prefix and yields the absolute path /prebuilts/clang/... at the filesystem
# root. The build does not complain; it just puts a nonexistent directory on
# PATH and the kernel dies at its first host tool with
# "/bin/sh: 1: clang: not found". BoardConfigKernel.mk:95 avoids this because
# '?=' is also recursively expanded.
TARGET_KERNEL_CLANG_PATH = $(BUILD_TOP)/prebuilts/clang/kernel/linux-x86/clang-r416183b
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

BOARD_PREBUILT_DTBOIMAGE := $(TARGET_KERNEL_PACKAGE)/dtbo.img
BOARD_PREBUILT_DTBIMAGE_DIR := $(TARGET_KERNEL_PACKAGE)/dtb
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# KMI gate inputs (see Android.mk and kmi-check.py).
#
# Every one of those prebuilt modules is version-checked at load time against
# whatever kernel we just built. The set includes UFS, display and the GPU, so a
# CRC disagreement is not a degraded boot — it is no boot. The build itself will
# NOT fail, which is the entire reason this gate exists.
#
# 0x7c24b32d is reproduced by CFI_CLANG=y + LTO_CLANG_FULL=y + MODVERSIONS=y from
# MediaTek's shipping config. CONFIG_CGROUP_DEVICE and CONFIG_CGROUP_PIDS also
# move it; USER_NS, PID_NS, DEVTMPFS and VT do not. The same KMI covers both
# module sets, so one kernel satisfies all 404.
BOARD_KMI_MODULE_LAYOUT := 0x7c24b32d
KMI_VENDOR_MODULES_DIR := $(TARGET_KERNEL_PACKAGE)/modules/vendor_dlkm
KMI_RAMDISK_MODULES_DIR := $(TARGET_KERNEL_PACKAGE)/modules/vendor_boot

# OPTIONAL: ship a kernel built by the separate custom-kernel project
# (itel-rs4-kernel) instead of compiling the GKI source in this tree.
#
# The two are deliberately different things and both are wanted:
#
#   kernel/itel/S666LN     plain GKI android12-5.10-lts + s666ln_defconfig. This
#                          is what the tree builds by default and what anyone
#                          cloning it reproduces exactly.
#   itel-rs4-kernel        the custom kernel project, which applies BORE and
#                          NTSYNC on top before building. Those patches live
#                          ONLY there, by design; they are not part of the GKI
#                          fork and must not be committed into it.
#
# Note the defconfig committed to the GKI fork still carries CONFIG_SCHED_BORE
# and CONFIG_NTSYNC. Kconfig drops both silently when the source lacks them, so
# a from-source build here is simply a kernel without those features -- not a
# broken one. Do not "fix" that by patching the fork.
#
# Run import-kernel.sh to populate this; absent it, the tree builds from source.
S666LN_CUSTOM_KERNEL := $(wildcard $(TARGET_KERNEL_PACKAGE)/prebuilt/Image.gz)
ifneq ($(S666LN_CUSTOM_KERNEL),)
    TARGET_PREBUILT_KERNEL := $(S666LN_CUSTOM_KERNEL)
    # Required: without it kernel.mk still compiles from source, because
    # TARGET_KERNEL_SOURCE exists (kernel.mk:128 vs :185).
    TARGET_FORCE_PREBUILT_KERNEL := true
    # FULL_KERNEL_BUILD is false in this mode, so $(KERNEL_OUT)/Module.symvers is
    # never produced. The custom kernel project emits the equivalent as
    # vmlinux.symvers; the KMI gate reads that instead, so an imported kernel is
    # checked against all 404 vendor modules exactly like a source-built one.
    KMI_SYMVERS := $(TARGET_KERNEL_PACKAGE)/prebuilt/vmlinux.symvers
endif

# Kernel modules. _LOAD is mandatory: if left unset the build defaults it to the
# FULL module list, and neither partition loads all of what it carries
# (vendor_dlkm ships 198 and loads 177; vendor_boot ships 206 and loads 171).
# Orders are stock's, recovered from the rev 28 vendor_boot ramdisk and
# vendor_dlkm image — see notes/kernel-modules-2026-08-04.md for both lists.
#
# That paragraph was written on 2026-08-04. The assignments below were not, and
# for two days the tree documented the trap directly above the code falling into
# it. The fallback is build/make/core/Makefile:447 —
#
#     $(if $(BOARD_$(1)_KERNEL_MODULES_LOAD$(_sep)$(_kver)),,\
#       $(eval BOARD_$(1)_KERNEL_MODULES_LOAD... := $(BOARD_$(1)_KERNEL_MODULES...)))
#
# — so modules.load shipped as all 206 .ko in $(wildcard) order. That put
# mtk_wdt.ko at position 143 instead of 12, and mkp.ko at 67 instead of 1. LK
# arms the hardware watchdog before it jumps to the kernel, so the AP was reset
# before its own watchdog driver ever probed. Build 19 died at ~5 s with
#
#     [pmic_check_rst] AP Watchdog / wdt_status 0x2 / aee_exp_type:2
#
# seven times, until the bootloader marked the slot unbootable. No panic, no
# logcat, no USB enumeration: an HWT leaves no mrdump, so the only trace of it
# was in the MediaTek expdb partition.
#
# Stock ships all 206 .ko in the ramdisk and loads 171 of them, so the wildcard
# is correct for _MODULES; only _LOAD was ever missing.
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(wildcard $(KMI_RAMDISK_MODULES_DIR)/*.ko)
BOARD_VENDOR_KERNEL_MODULES := \
    $(wildcard $(KMI_VENDOR_MODULES_DIR)/*.ko)

# Read the orders from the lists that ship beside the .ko files rather than
# copying 547 module names in here, so the two cannot drift. _LOAD takes full
# paths and must be a subset of _MODULES above; the build writes $(notdir) of
# each into modules.load, in this order.
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_RAMDISK_MODULES_DIR)/,\
        $(shell cat $(KMI_RAMDISK_MODULES_DIR)/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_RAMDISK_MODULES_DIR)/,\
        $(shell cat $(KMI_RAMDISK_MODULES_DIR)/modules.load.recovery))
BOARD_VENDOR_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_VENDOR_MODULES_DIR)/,\
        $(shell cat $(KMI_VENDOR_MODULES_DIR)/modules.load))

# A missing or unreadable list expands to nothing, which is indistinguishable
# from never setting _LOAD at all — i.e. silently back to the bug above. Fail
# the build instead of shipping another watchdog reset.
ifeq ($(strip $(BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD)),)
    $(error S666LN: $(KMI_RAMDISK_MODULES_DIR)/modules.load is missing or empty)
endif
ifeq ($(strip $(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD)),)
    $(error S666LN: $(KMI_RAMDISK_MODULES_DIR)/modules.load.recovery is missing or empty)
endif
ifeq ($(strip $(BOARD_VENDOR_KERNEL_MODULES_LOAD)),)
    $(error S666LN: $(KMI_VENDOR_MODULES_DIR)/modules.load is missing or empty)
endif

# Recovery lives in vendor_boot; there is no dedicated recovery partition. [V]
#
# BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT is what actually enables
# BUILDING_RECOVERY_IMAGE for this layout (board_config.mk:501). Recovery
# resources ARE built — they are just packed into vendor_boot rather than a
# recovery.img. Without it, BUILDING_RECOVERY_IMAGE stays unset and
# BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE below errors out at line 1068.
#
# BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT is a separate, complementary
# variable; setting it alone does NOT enable recovery-resource building.
#
# TARGET_RECOVERY_FSTAB is load-bearing for the OTA ZIP, not just for recovery.
# build/make/core/Makefile:5021 does
#     ifeq ($(recovery_fstab),)
#       build_ota_package := false
#     endif
# and recovery_fstab (line 2337) is TARGET_RECOVERY_FSTAB, else a genrule, else
# $(TARGET_DEVICE_DIR)/recovery.fstab. This tree keeps its fstab under rootdir/
# and has no recovery.fstab, so with the variable unset all three fall through to
# empty and OTA packaging turns itself off silently.
#
# Nothing errors at that point. INTERNAL_OTA_PACKAGE_TARGET just becomes empty,
# so `bacon` ends up with no prerequisite and its recipe runs as
#     mv -f  out/.../crDroidAndroid-*.zip
# failing 3000 lines later with "mv: Needs 2 arguments" -- which says nothing
# about fstabs. Point it at the same fstab first-stage init and /vendor use.
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6789

BOARD_USES_RECOVERY_AS_BOOT :=
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
TARGET_NO_RECOVERY := true
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true

# Partition sizes                                                       [V]
# super: block device 9,847,996,416 B (scatter 0x24AFC8000), group max
# 9,845,899,264 B — both read back from the stock super metadata (lpdump).
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
# 8 MiB, NOT 32. Read off the device (blockdev --getsize64
# /dev/block/by-name/dtbo_a = 8388608), and it agrees with both stock's dtbo.img
# and the prebuilt in device/itel/S666LN-kernel, which are 8388608 bytes each.
#
# The 32 MiB value here was wrong and this whole block was marked [V] anyway.
# Nothing catches it at build time: the actual DTB payload is only 112,384 bytes,
# so avbtool happily pads the image out to whatever partition size is declared
# and produces a perfectly valid 32 MiB dtbo.img. It fails at FLASH time, four
# partitions into the payload:
#
#   Failed to perform REPLACE_BZ operation 36 ... in partition "dtbo"
#   Failed to flush cached data!: No space left on device (28)
#   ErrorCode::kDownloadOperationExecutionError (28)
#
# Verify partition sizes against the hardware, not against the scatter file.
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

BOARD_SUPER_PARTITION_SIZE := 9847996416
BOARD_SUPER_PARTITION_GROUPS := mtk_dynamic_partitions

# Group max is DELIBERATELY well under the super size, and must stay that way.
#
# update_engine refuses a sideload when the sum of the target's group maxima
# exceeds the allocatable space of the super ALREADY ON THE DEVICE:
#
#   [ERROR] The maximum size of all groups for the target slot (9845899264) has
#           exceeded allocatable space for dynamic partitions 9125756928.
#   [ERROR] Error ErrorCode::kInstallDeviceOpenError (7)
#
# That check reads allocatable space from the EXISTING metadata, not from the
# block device. This device's super really is 9,847,996,416 B and stock's
# metadata says so, but a previously-installed ROM had written metadata
# declaring 9,126,805,504 — so every user coming from that ROM hit a hard
# install failure, while anyone coming from stock did not. That asymmetry is why
# it survived to a flash attempt.
#
# Claiming the whole super bought nothing: these six partitions total ~2.05 GB.
#
# Do NOT "restore" this to the stock 9845899264 to match lpdump. It is not a
# fidelity value; it is a compatibility ceiling.
#
# 🔴 LOWERED 8 GiB -> 4 GiB, 2026-08-11, measured on hardware. 8 GiB installs
# through OrangeFox and CANNOT be sideloaded from our own recovery:
#
#   [ERROR:dynamic_partition_control_android.cc(916)] The maximum size of all
#     groups for the target slot (8589934592) has exceeded HALF OF allocatable
#     space for dynamic partitions 4923473920.
#
# The load-bearing words are "HALF OF". update_engine halves the budget when it
# cannot use Virtual A/B snapshots, because then BOTH slots' partitions must be
# resident in super at once. In recovery it cannot: update_engine_sideload links
# the snapshot STUB, which announces itself in the same log --
#
#   snapshot_stub.cpp:168  UnmapAllSnapshots should never be called
#
# -- and `ro.virtual_ab.enabled` reads empty there. That is how sideload works on
# this platform, not a misconfiguration to chase.
#
# So the ceiling is half of allocatable space in the SMALLEST super geometry
# seen in the field, not all of it:
#
#   stock super       9,846,947,840 allocatable  ->  half  4,923,473,920
#   other ROM's super 9,125,756,928 allocatable  ->  half  4,562,878,464   <- binding
#   this value        4,294,967,296                     fits both, 268 MB spare
#   actual content    ~2.05 GB                          2x headroom remains
#
# Why this was invisible until now: OrangeFox carries full snapshot support, so
# it got the WHOLE allocatable space and 8 GiB passed. Every install this
# project has ever done went through it. The value was only ever tested against
# the one recovery that hides the constraint -- and shipping our own recovery is
# precisely what stops hiding it. Anyone sideloading this ROM without OrangeFox
# would have hit this, so it is a release blocker, not a local inconvenience.
#
# Lower this further only against a measurement; raising it breaks sideload.
BOARD_MTK_DYNAMIC_PARTITIONS_SIZE := 4294967296
BOARD_MTK_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    odm_dlkm \
    product \
    system \
    system_ext \
    vendor \
    vendor_dlkm

# Filesystems — stock uses erofs for the read-mostly partitions and ext4
# for the two dlkm ones.                                                [V]
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_EROFS_COMPRESSOR := lz4hc,9
BOARD_EROFS_PCLUSTER_SIZE := 262144

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Vendor security patch level. THIS IS LOAD-BEARING; it is not cosmetic.
#
# build/make/core/main.mk does
#     ADDITIONAL_VENDOR_PROPERTIES += ro.vendor.build.security_patch=$(VENDOR_SECURITY_PATCH)
# and nothing anywhere else in the tree defines VENDOR_SECURITY_PATCH, so
# without this line the property ships EMPTY:
#     ro.vendor.build.security_patch=
#
# The Trustonic KeyMint HAL reads it to set Tag::VENDOR_PATCHLEVEL. An empty
# value leaves the TA unconfigured, and every generateKey then fails with
# KeyMint error -49 (KEYMINT_NOT_CONFIGURED). vold cannot mint the metadata
# encryption key, /data cannot be prepared, and init reboots to recovery:
#     vold: keystore2 Keystore generateKey returned service specific error: -49
#     vold: read_key failed in mountFstab
#     vdc: Command: cryptfs init_user0 Failed
#     reboot: Restarting system with command 'recovery'
# which presents as a bootloop, not as a keystore error.
#
# 2025-04-05 is what stock ships (vendor_ex/build.prop). It must match stock
# rather than PLATFORM_SECURITY_PATCH, because the vendor blobs ARE that stock
# build and the TA was provisioned against it.
VENDOR_SECURITY_PATCH := 2025-04-05

# Metadata / Virtual A/B                                                [V]
#
# Only the BOARD_* half belongs here. PRODUCT_USE_DYNAMIC_PARTITIONS and
# PRODUCT_VIRTUAL_AB_OTA are product variables: board_config.mk marks PRODUCT_*
# readonly before it includes this file, so assigning them here fails with
# "cannot assign to readonly variable". They live in device.mk instead.
BOARD_USES_METADATA_PARTITION := true

# AVB. The stock chain is signed with the public AOSP test key, so this
# offers no real protection; it is kept as-is so verified boot stays green
# under the device's patched LK. Real signing keys are a ROM decision and
# belong in the build recipe, not here.                                 [V]
BOARD_AVB_ENABLE := true
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_ROLLBACK_INDEX := 1
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
BOARD_AVB_VBMETA_SYSTEM := product system system_ext
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2

# vbmeta_vendor. AB_OTA_PARTITIONS lists it, but without this block the build
# never creates the image and target-files packaging dies with
#   AssertionError: Failed to find vbmeta_vendor.img
# at 99%, after every partition image has already been built.
#
# Contents and rollback index location read back from the stock images with
# avbtool info_image, not guessed:
#
#   stock vbmeta        chains boot (RIL 3), vbmeta_system (RIL 2),
#                       vbmeta_vendor (RIL 4), and carries direct descriptors
#                       for dtbo, vendor_boot, odm_dlkm, system_ext, vendor_dlkm
#   stock vbmeta_vendor exactly one hashtree descriptor: vendor
#
# So vbmeta_vendor chains ONLY vendor. vendor_dlkm and odm_dlkm are deliberately
# not listed: stock keeps them in the main vbmeta, and moving them here would
# change which image the bootloader must verify them from.
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 4

# Display                                                              [V]
TARGET_SCREEN_DENSITY := 273

# Properties — a value containing a space must be set through these raw
# .prop files, not PRODUCT_*_PROPERTIES.
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/configs/properties/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/configs/properties/vendor.prop

# SELinux
include device/mediatek/sepolicy_vndr/SEPolicy.mk
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/public
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# Hardware
#
# BOARD_HAS_MTK_HARDWARE gates hardware/mediatek/Android.mk, which is
#   ifeq ($(BOARD_HAS_MTK_HARDWARE),true)
#   include $(call all-subdir-makefiles)
#   endif
# Without it none of that repo's make-based modules are built AND the nested
# hardware/mediatek/wlan is never descended into, so libwifi-hal-mt66xx does not
# exist and frameworks/opt/net/wifi fails with
#   "libwifi-hal (SHARED_LIBRARIES) missing libwifi-hal-mt66xx (STATIC_LIBRARIES)".
# Its Android.bp modules are picked up regardless, which is why the soong-side
# collisions appeared before this was noticed.
BOARD_HAS_MTK_HARDWARE := true
BOARD_HAVE_BLUETOOTH := true
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211

# 🔴 THIS LINE IS WHY WI-FI WORKS. Without it wpa_supplicant is built and
# installed but has NO INIT SERVICE, so nothing can ever start it.
#
# external/wpa_supplicant_8/wpa_supplicant/Android.mk:1828 gates the daemon's
# own rc on it, and nothing else in the whole tree sets it:
#
#   ifeq ($(WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY), true)
#   LOCAL_INIT_RC=aidl/android.hardware.wifi.supplicant-service.rc
#   endif
#
# Measured on hardware, build 54, before this line existed:
#
#   /vendor/bin/hw/wpa_supplicant            present, 3,098,984 B
#   /vendor/etc/init/*supplicant*            ABSENT  (93 files, none matching)
#   /dev/socket/wpa_wlan0                    ABSENT  (init never made the socket)
#   getprop init.svc.wpa_supplicant          empty
#   cmd wifi set-wifi-enabled enabled     -> "Wifi is disabled"
#   E WifiThreadRunner: at WifiNative.startAndWaitForSupplicantConnection:555
#                       at WifiNative.startSupplicant:579
#
# PROVEN live, single variable, demonstrated BOTH ways on the running device:
# starting the daemon by hand with the exact arguments this rc uses made
# ISupplicant/default register, Wi-Fi enable, ClientModeManager come up as
# ROLE_CLIENT_PRIMARY on wlan0, scan 11 APs across 2.4 and 5 GHz, associate to
# a WPA2 AP (802.11ac, 390 Mbps), take a DHCP lease and ping 8.8.8.8 at 15 ms
# with 0% loss. Killing the daemon put it straight back to "Wifi is disabled";
# restarting it restored everything.
#
# Note the AIDL half was already correct and needs no flag here:
# WPA_SUPPLICANT_USE_AIDL defaults on, so the daemon links
# android.hardware.wifi.supplicant-V1-ndk.so and the module ships its own
# VINTF fragment. Only the rc was gated, and only by this variable.
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true

# Inherit the proprietary blob makefiles
include vendor/itel/S666LN/BoardConfigVendor.mk
