#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Values marked [V] were re-derived from itel stock firmware revision 28
# (build 251212V1661) and/or the live device. Values marked [C] are carried
# forward and still want an independent check — see notes/ for status.
#

DEVICE_PATH := device/itel/S666LN

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    odm_dlkm \
    product \
    system \
    system_ext \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_boot \
    vendor_dlkm

# Architecture                                                          [V]
# Helio G99: 2x Cortex-A76 @2.2GHz + 6x Cortex-A55 @2.0GHz
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a76
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

# Bootloader                                                            [V]
TARGET_BOOTLOADER_BOARD_NAME := s666ln
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6789

# Kernel — GKI. This device ships a PREBUILT kernel image; the ROM does not
# compile it. See device/itel/S666LN-kernel.                             [V]
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_RAMDISK_USE_LZ4 := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096

# Stock boot.img ships an EMPTY cmdline; the one boot parameter lives in
# vendor_boot's cmdline field, and vendor_boot's bootconfig section is zero
# bytes. That is also what the build does with this variable at header v4 —
# BOARD_KERNEL_CMDLINE is passed as --vendor_cmdline, not into boot.img — so
# setting it here reproduces stock. Everything else the kernel sees
# (androidboot.hardware=mt6789 &c.) is appended by the MediaTek LK at boot,
# not stored in any image we build.
#
# NOT reproduced from the old tree: androidboot.selinux=permissive (this tree
# runs enforcing) and sysctl.kernel.sched_pelt_multiplier=4 (absent from stock
# revision 28; it is a kernel/ROM tuning choice, not a device fact).   [V]
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2

# Offsets                                                               [V]
# Read back from the stock vendor_boot header (v4, page 4096):
#   kernel_addr  0x40000000 = base + kernel_offset
#   ramdisk_addr 0x66f00000 = base + ramdisk_offset
#   tags_addr    0x47c80000 = base + tags_offset
#   dtb_addr     0x47c80000 = base + dtb_offset
# All four reconstruct exactly from the values below.
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_KERNEL_TAGS_OFFSET := 0x07c88000
BOARD_DTB_OFFSET := 0x07c88000

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)

# Kernel — built FROM SOURCE, with prebuilt dtb/dtbo/modules alongside.
#
# Only the Image is compiled. The dtb, dtbo and all 404 vendor modules (198
# vendor_dlkm + 206 vendor_boot) remain MediaTek prebuilts: they are not part of
# GKI and there is no source for them.
#
# SINGLE SOURCE OF TRUTH for the config: s666ln_defconfig lives in the kernel
# source repo at arch/arm64/configs/, is generated by the kernel project's
# build.sh (stock.config + performance + network + bore + ntsync, merged and
# olddefconfig'd) and committed there. Both the kernel project and this ROM build
# read that one file, so they cannot drift.
#
# Do NOT pass a list here. LineageOS documents TARGET_KERNEL_CONFIG as "list of
# defconfigs, first being the base", but make-kernel-config passes them straight
# to Kbuild as make targets — and stock GKI Kbuild runs them sequentially, last
# one winning, with no merge. A list would silently build the wrong config.
#
# gki_defconfig does NOT work: the config is what fixes the symbol CRCs, so a
# wrong defconfig yields a kernel that builds fine and boots nothing.
#
# ⚠ Never set KERNEL_LTO. kernel.mk honours it (thin/full/none) by rewriting
# LTO_CLANG_FULL after the defconfig is applied — which changes module_layout and
# breaks every vendor module. The KMI gate below will catch it, but the fix is to
# leave the variable alone.
TARGET_KERNEL_PACKAGE := device/itel/S666LN-kernel
TARGET_KERNEL_SOURCE := kernel/itel/S666LN
TARGET_KERNEL_CONFIG := s666ln_defconfig
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_CLANG_VERSION := r416183b
# BoardConfigKernel.mk:95 would resolve this to prebuilts/clang/host/..., which
# on a LineageOS 20 tree only ever contains clang-r450784d. r416183b ships as its
# own LineageOS project under prebuilts/clang/kernel/ -- see S666LN.xml.
#
# NOTE the '=' -- this MUST be a recursively-expanded assignment. BUILD_TOP is
# not defined yet when BoardConfig.mk is parsed, so ':=' bakes in an empty
# prefix and yields the absolute path /prebuilts/clang/... at the filesystem
# root. The build does not complain; it just puts a nonexistent directory on
# PATH and the kernel dies at its first host tool with
# "/bin/sh: 1: clang: not found". BoardConfigKernel.mk:95 avoids this because
# '?=' is also recursively expanded.
TARGET_KERNEL_CLANG_PATH = $(BUILD_TOP)/prebuilts/clang/kernel/linux-x86/clang-r416183b
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

BOARD_PREBUILT_DTBOIMAGE := $(TARGET_KERNEL_PACKAGE)/dtbo.img
BOARD_PREBUILT_DTBIMAGE_DIR := $(TARGET_KERNEL_PACKAGE)/dtb
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# KMI gate inputs (see Android.mk and kmi-check.py).
#
# Every one of those prebuilt modules is version-checked at load time against
# whatever kernel we just built. The set includes UFS, display and the GPU, so a
# CRC disagreement is not a degraded boot — it is no boot. The build itself will
# NOT fail, which is the entire reason this gate exists.
#
# 0x7c24b32d is reproduced by CFI_CLANG=y + LTO_CLANG_FULL=y + MODVERSIONS=y from
# MediaTek's shipping config. CONFIG_CGROUP_DEVICE and CONFIG_CGROUP_PIDS also
# move it; USER_NS, PID_NS, DEVTMPFS and VT do not. The same KMI covers both
# module sets, so one kernel satisfies all 404.
BOARD_KMI_MODULE_LAYOUT := 0x7c24b32d
KMI_VENDOR_MODULES_DIR := $(TARGET_KERNEL_PACKAGE)/modules/vendor_dlkm

# Kernel modules. _LOAD is mandatory: if left unset the build defaults it to the
# FULL module list, and neither partition loads all of what it carries
# (vendor_dlkm ships 198 and loads 177; vendor_boot ships 206 and loads 171).
# Orders are stock's, recovered from the rev 28 vendor_boot ramdisk and
# vendor_dlkm image — see notes/kernel-modules-2026-08-04.md for both lists.
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(wildcard $(TARGET_KERNEL_PACKAGE)/modules/vendor_boot/*.ko)
BOARD_VENDOR_KERNEL_MODULES := \
    $(wildcard $(KMI_VENDOR_MODULES_DIR)/*.ko)

# Recovery lives in vendor_boot; there is no dedicated recovery partition. [V]
#
# BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT is what actually enables
# BUILDING_RECOVERY_IMAGE for this layout (board_config.mk:501). Recovery
# resources ARE built — they are just packed into vendor_boot rather than a
# recovery.img. Without it, BUILDING_RECOVERY_IMAGE stays unset and
# BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE below errors out at line 1068.
#
# BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT is a separate, complementary
# variable; setting it alone does NOT enable recovery-resource building.
#
# TARGET_RECOVERY_FSTAB is load-bearing for the OTA ZIP, not just for recovery.
# build/make/core/Makefile:5021 does
#     ifeq ($(recovery_fstab),)
#       build_ota_package := false
#     endif
# and recovery_fstab (line 2337) is TARGET_RECOVERY_FSTAB, else a genrule, else
# $(TARGET_DEVICE_DIR)/recovery.fstab. This tree keeps its fstab under rootdir/
# and has no recovery.fstab, so with the variable unset all three fall through to
# empty and OTA packaging turns itself off silently.
#
# Nothing errors at that point. INTERNAL_OTA_PACKAGE_TARGET just becomes empty,
# so `bacon` ends up with no prerequisite and its recipe runs as
#     mv -f  out/.../crDroidAndroid-*.zip
# failing 3000 lines later with "mv: Needs 2 arguments" -- which says nothing
# about fstabs. Point it at the same fstab first-stage init and /vendor use.
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6789

BOARD_USES_RECOVERY_AS_BOOT :=
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
TARGET_NO_RECOVERY := true
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true

# Partition sizes                                                       [V]
# super: block device 9,847,996,416 B (scatter 0x24AFC8000), group max
# 9,845,899,264 B — both read back from the stock super metadata (lpdump).
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 33554432

BOARD_SUPER_PARTITION_SIZE := 9847996416
BOARD_SUPER_PARTITION_GROUPS := mtk_dynamic_partitions
BOARD_MTK_DYNAMIC_PARTITIONS_SIZE := 9845899264
BOARD_MTK_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    odm_dlkm \
    product \
    system \
    system_ext \
    vendor \
    vendor_dlkm

# Filesystems — stock uses erofs for the read-mostly partitions and ext4
# for the two dlkm ones.                                                [V]
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_EROFS_COMPRESSOR := lz4hc,9
BOARD_EROFS_PCLUSTER_SIZE := 262144

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Metadata / Virtual A/B                                                [V]
#
# Only the BOARD_* half belongs here. PRODUCT_USE_DYNAMIC_PARTITIONS and
# PRODUCT_VIRTUAL_AB_OTA are product variables: board_config.mk marks PRODUCT_*
# readonly before it includes this file, so assigning them here fails with
# "cannot assign to readonly variable". They live in device.mk instead.
BOARD_USES_METADATA_PARTITION := true

# AVB. The stock chain is signed with the public AOSP test key, so this
# offers no real protection; it is kept as-is so verified boot stays green
# under the device's patched LK. Real signing keys are a ROM decision and
# belong in the build recipe, not here.                                 [V]
BOARD_AVB_ENABLE := true
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_ROLLBACK_INDEX := 1
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
BOARD_AVB_VBMETA_SYSTEM := product system system_ext
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2

# Display                                                              [V]
TARGET_SCREEN_DENSITY := 273

# Properties — a value containing a space must be set through these raw
# .prop files, not PRODUCT_*_PROPERTIES.
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/configs/properties/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/configs/properties/vendor.prop

# SELinux
include device/mediatek/sepolicy_vndr/SEPolicy.mk
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/public
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# Hardware
#
# BOARD_HAS_MTK_HARDWARE gates hardware/mediatek/Android.mk, which is
#   ifeq ($(BOARD_HAS_MTK_HARDWARE),true)
#   include $(call all-subdir-makefiles)
#   endif
# Without it none of that repo's make-based modules are built AND the nested
# hardware/mediatek/wlan is never descended into, so libwifi-hal-mt66xx does not
# exist and frameworks/opt/net/wifi fails with
#   "libwifi-hal (SHARED_LIBRARIES) missing libwifi-hal-mt66xx (STATIC_LIBRARIES)".
# Its Android.bp modules are picked up regardless, which is why the soong-side
# collisions appeared before this was noticed.
BOARD_HAS_MTK_HARDWARE := true
BOARD_HAVE_BLUETOOTH := true
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211

# Inherit the proprietary blob makefiles
include vendor/itel/S666LN/BoardConfigVendor.mk
